name: Test Windows Install
on: workflow_dispatch
jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Run installer
        run: powershell -c "irm clams-website-preview.surge.sh/install.ps1 | iex"
      - name: Verify
        run: clams --version
