name: Test Windows Install
on: workflow_dispatch
jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Run installer
        run: powershell -c "irm https://raw.githubusercontent.com/clams-tech/clams.tech/main/website/public/install.ps1 | iex"
      - name: Verify
        run: clams --version
