name: Test Windows Install
on: workflow_dispatch
jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Run installer
        run: powershell -ExecutionPolicy Bypass -c "irm https://github.com/clams-tech/releases/releases/download/clams-v1.0.0-beta.1/clams-installer.ps1 | iex"
      - name: Verify
        run: clams --version
